-- 10월에 대여 시작 기록이 있는 세단 자동차
-- SELECT CAR_ID
SELECT DISTINCT CAR_ID
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE CAR_ID in (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_CAR
    WHERE CAR_TYPE = '세단'
)
AND
    START_DATE like '%-10-%'
ORDER BY CAR_ID desc;